Настройка

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -3,38 +3,93 @@ on:
   push:
     branches:
       - master
+      - develop
   pull_request:
     branches:
       - master
+      - develop
 jobs:
   build:
-    name: Autograding
+    name: Build Project
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
-      # TODO build, test and deploy project
+      - name: Build dockerfile for app
+        run: |
+          docker build -t person:latest ./ --target=release
+          docker commit person:latest person-image:latest
+          docker save person-image:latest > person.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: person-artefact 
+          path: person.tar
+      
+      - name: Build dockerfile for tests
+        run: |
+          docker build -t person-tests:latest ./ --target=build
+          docker commit person-tests:latest person-tests-image:latest
+          docker save person-tests-image:latest > person-tests.tar
+      - uses: actions/upload-artifact@v4 
+        with: 
+          name: person-tests-artefact 
+          path: person-tests.tar
 
-      - name: Run API Tests
-        uses: matt-ball/newman-action@master
+  test:
+    name: Test Project
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - uses: actions/checkout@v3
         with:
-          collection: postman/[inst] Lab1.postman_collection.json
-          environment: postman/[inst][heroku] Lab1.postman_environment.json
-          delayRequest: 100
-          reporters: '[ "cli" ]'
+          fetch-depth: 0
+      
+      - uses: actions/download-artifact@v4
+        with: 
+          name: person-tests-artefact 
 
-      - name: Autograding
-        uses: education/autograding@v1
-        continue-on-error: true
+      - name: Run Unit Tests
+        run: |
+          docker load < person-tests.tar
+          docker compose -f ./docker-compose.tests.yml --project-directory ./ up --exit-code-from person_service_tests
+          if [[ 0 == $? ]]
+          then
+            echo "TESTS_STATUS=success" >> $GITHUB_ENV
+          else
+            echo "TESTS_STATUS=failed" >> $GITHUB_ENV
+          fi
 
-      - name: Github auto grader mark
-        uses: Romanow/google-sheet-autograder-marker@v1.0
-        with:
-          google_token: ${{secrets.GOOGLE_API_KEY}}
-          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
-          homework_number: 1
-          user_column: 'D'
-          column_offset: 'F'
-          mark: "'+"
+
+
+
+  # build:
+  #   name: Autograding
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
+  #       with:
+  #         fetch-depth: 0
+
+  #     - name: Run API Tests
+  #       uses: matt-ball/newman-action@master
+  #       with:
+  #         collection: postman/[inst] Lab1.postman_collection.json
+  #         environment: postman/[inst][heroku] Lab1.postman_environment.json
+  #         delayRequest: 100
+  #         reporters: '[ "cli" ]'
+
+  #     - name: Autograding
+  #       uses: education/autograding@v1
+  #       continue-on-error: true
+
+  #     - name: Github auto grader mark
+  #       uses: Romanow/google-sheet-autograder-marker@v1.0
+  #       with:
+  #         google_token: ${{secrets.GOOGLE_API_KEY}}
+  #         sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
+  #         homework_number: 1
+  #         user_column: 'D'
+  #         column_offset: 'F'
+  #         mark: "'+"
